server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        autoindex on;
    }

    location /reports/ {
        alias /usr/share/nginx/html/reports/;
        autoindex on;
        add_header Content-Type text/plain;
    }

    location /evidence/ {
        alias /usr/share/nginx/html/evidence/;
        autoindex on;
    }
}
